version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20.16
  build:
    commands:
      - npm install
      - npm run build
  post_build:
  commands:
    - ls -la ./dist/
    - aws s3 sync ./dist/ s3://roflstudios.com/ --delete
artifacts:
  files:
    - "**/*"
